<Project Sdk="Aspire.AppHost.Sdk/13.2.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Agentstration.Web/Agentstration.Web.csproj" />
    <ProjectReference Include="../Agentstration.Work.Api/Agentstration.Work.Api.csproj" />
    <ProjectReference Include="../Agentstration.Workplace.Web/Agentstration.Workplace.Web.csproj" />
    <ProjectReference Include="../Agentstration.Extensions.Ollama/Agentstration.Extensions.Ollama.csproj" />
    <ProjectReference Include="../Agentstration.Extensions.Utilities/Agentstration.Extensions.Utilities.csproj" />
  </ItemGroup>
</Project>
