<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="../ApiModuleGlobalUsings.cs" Link="GlobalUsings.cs" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Agentstration.Api.Contracts/Agentstration.Api.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.Identity/Agentstration.Identity.csproj" />
    <ProjectReference Include="../Agentstration.Identity.Contracts/Agentstration.Identity.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.ResourceManagement/Agentstration.ResourceManagement.csproj" />
    <ProjectReference Include="../Agentstration.Resources/Agentstration.Resources.csproj" />
    <ProjectReference Include="../Agentstration.Security.AspNetCoreIdentity/Agentstration.Security.AspNetCoreIdentity.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
  </ItemGroup>
</Project>
