<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup Condition="'$(UseLocalAepProjects)' == 'true'">
    <ProjectReference Include="../../aep/src/Agentstration.Aep.Client/Agentstration.Aep.Client.csproj" />
    <ProjectReference Include="../../aep/src/Agentstration.Aep.MicrosoftExtensionsAI/Agentstration.Aep.MicrosoftExtensionsAI.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(UseLocalAepProjects)' != 'true'">
    <PackageReference Include="Agentstration.Aep.Client" />
    <PackageReference Include="Agentstration.Aep.MicrosoftExtensionsAI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Agentstration.Management.Abstractions/Agentstration.Management.Abstractions.csproj" />
    <ProjectReference Include="../Agentstration.Runtime.Abstractions/Agentstration.Runtime.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
