<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Agentstration.Agents/Agentstration.Agents.csproj" />
    <ProjectReference Include="../Agentstration.Management.Abstractions/Agentstration.Management.Abstractions.csproj" />
    <ProjectReference Include="../Agentstration.Models/Agentstration.Models.csproj" />
    <ProjectReference Include="../Agentstration.Runtime.Abstractions/Agentstration.Runtime.Abstractions.csproj" />
    <ProjectReference Include="../Agentstration.Secrets/Agentstration.Secrets.csproj" />
    <ProjectReference Include="../Agentstration.ResourceManagement/Agentstration.ResourceManagement.csproj" />
    <ProjectReference Include="../Agentstration.Tools/Agentstration.Tools.csproj" />
    <ProjectReference Include="../Agentstration.Triggers/Agentstration.Triggers.csproj" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
