<Project Sdk="MSTest.Sdk/4.3.3">
  <ItemGroup>
    <ProjectReference Include="../../src/Agentstration.Web/Agentstration.Web.csproj" />
  <ProjectReference Include="../../src/Agentstration.Web.Components/Agentstration.Web.Components.csproj" />
  <PackageReference Include="bunit" />
  </ItemGroup>
</Project>
