<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Agentstration.Web.Components/Agentstration.Web.Components.csproj" />
    <ProjectReference Include="../Agentstration.Workplace.Components/Agentstration.Workplace.Components.csproj" />
    <ProjectReference Include="../Agentstration.Workplace.Client/Agentstration.Workplace.Client.csproj" />
    <ProjectReference Include="../Agentstration.Work.Contracts/Agentstration.Work.Contracts.csproj" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="OpenTelemetry.Extensions.Hosting" /><PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" /><PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" /><PackageReference Include="OpenTelemetry.Instrumentation.Http" /></ItemGroup>
</Project>
