<Project Sdk="MSTest.Sdk/4.3.3">
  <ItemGroup>
    <ProjectReference Include="../../src/Agentstration.Workplace.Web/Agentstration.Workplace.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
</Project>
