<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="../ApiModuleGlobalUsings.cs" Link="GlobalUsings.cs" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Agentstration.Api.Contracts/Agentstration.Api.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.Bootstrap.Contracts/Agentstration.Bootstrap.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.Identity.Contracts/Agentstration.Identity.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.ResourceManagement.Contracts/Agentstration.ResourceManagement.Contracts.csproj" />
  </ItemGroup>
</Project>
