<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Agentstration.Aep.Abstractions/Agentstration.Aep.Abstractions.csproj" />
    <ProjectReference Include="../Agentstration.Aep.AspNetCore/Agentstration.Aep.AspNetCore.csproj" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="OllamaSharp" /></ItemGroup>
</Project>
