<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Agentstration.Aep.Inspector/Agentstration.Aep.Inspector.csproj" />
  </ItemGroup>
</Project>
