using System.Data;
using System.Text.Json;
using Agentstration.Management.Abstractions;
using Microsoft.EntityFrameworkCore;

namespace Agentstration.Management.Storage.Sqlite;

internal sealed class TenantRow { public Guid Id { get; set; } public required string Name { get; set; } public required string DisplayName { get; set; } public TenantStatus Status { get; set; } public DateTimeOffset CreatedAt { get; set; } }
internal sealed class WorkspaceRow { public Guid Id { get; set; } public Guid TenantId { get; set; } public required string Name { get; set; } public required string DisplayName { get; set; } public WorkspaceStatus Status { get; set; } public DateTimeOffset CreatedAt { get; set; } }
internal sealed class PrincipalRow { public Guid Id { get; set; } public string? LegacyExternalSubject { get; set; } public PrincipalKind Kind { get; set; } public required string DisplayName { get; set; } public string? Email { get; set; } public PrincipalStatus Status { get; set; } public DateTimeOffset CreatedAt { get; set; } }
internal sealed class ExternalIdentityRow { public Guid Id { get; set; } public required string Issuer { get; set; } public required string Subject { get; set; } public Guid PrincipalId { get; set; } public DateTimeOffset LinkedAt { get; set; } }
internal sealed class LocalIdentityRow { public Guid AccountId { get; set; } public Guid PrincipalId { get; set; } public DateTimeOffset LinkedAt { get; set; } }
internal sealed class PlatformAdministratorRow { public Guid PrincipalId { get; set; } public DateTimeOffset GrantedAt { get; set; } }
internal sealed class TenantMembershipRow { public Guid Id { get; set; } public Guid TenantId { get; set; } public Guid PrincipalId { get; set; } public MembershipStatus Status { get; set; } public DateTimeOffset JoinedAt { get; set; } }
internal sealed class WorkspaceMembershipRow { public Guid Id { get; set; } public Guid WorkspaceId { get; set; } public Guid PrincipalId { get; set; } public MembershipStatus Status { get; set; } public DateTimeOffset JoinedAt { get; set; } }
internal sealed class RoleDefinitionRow { public Guid Id { get; set; } public required string Name { get; set; } public required string DisplayName { get; set; } public required string PermissionsJson { get; set; } public bool IsBuiltIn { get; set; } }
internal sealed class RoleAssignmentRow { public Guid Id { get; set; } public Guid TenantId { get; set; } public Guid PrincipalId { get; set; } public PrincipalType PrincipalType { get; set; } public Guid RoleDefinitionId { get; set; } public required string Scope { get; set; } }
internal sealed class SecurityAuditRow { public Guid Id { get; set; } public required string Action { get; set; } public SecurityAuditOutcome Outcome { get; set; } public Guid? ActorPrincipalId { get; set; } public Guid? TargetPrincipalId { get; set; } public Guid? TargetAccountId { get; set; } public Guid? TenantId { get; set; } public Guid? WorkspaceId { get; set; } public string? ReasonCode { get; set; } public string? CorrelationId { get; set; } public long OccurredAtUtcTicks { get; set; } }

internal static class IdentityModel
{
    public static void ConfigureIdentityModel(this ModelBuilder modelBuilder)
    {
        var tenant = modelBuilder.Entity<TenantRow>(); tenant.ToTable("Tenants"); tenant.HasKey(x => x.Id); tenant.HasIndex(x => x.Name).IsUnique();
        var workspace = modelBuilder.Entity<WorkspaceRow>(); workspace.ToTable("Workspaces"); workspace.HasKey(x => x.Id); workspace.HasIndex(x => new { x.TenantId, x.Name }).IsUnique(); workspace.HasOne<TenantRow>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Cascade);
        var principal = modelBuilder.Entity<PrincipalRow>(); principal.ToTable("Users"); principal.HasKey(x => x.Id); principal.Property(x => x.LegacyExternalSubject).HasColumnName("ExternalSubject");
        var externalIdentity = modelBuilder.Entity<ExternalIdentityRow>(); externalIdentity.ToTable("ExternalIdentities"); externalIdentity.HasKey(x => x.Id); externalIdentity.HasIndex(x => new { x.Issuer, x.Subject }).IsUnique(); externalIdentity.HasIndex(x => x.PrincipalId); externalIdentity.HasOne<PrincipalRow>().WithMany().HasForeignKey(x => x.PrincipalId).OnDelete(DeleteBehavior.Cascade);
        var localIdentity = modelBuilder.Entity<LocalIdentityRow>(); localIdentity.ToTable("LocalIdentities"); localIdentity.HasKey(x => x.AccountId); localIdentity.HasIndex(x => x.PrincipalId).IsUnique(); localIdentity.HasOne<PrincipalRow>().WithMany().HasForeignKey(x => x.PrincipalId).OnDelete(DeleteBehavior.Cascade);
        var platformAdministrator = modelBuilder.Entity<PlatformAdministratorRow>(); platformAdministrator.ToTable("PlatformAdministrators"); platformAdministrator.HasKey(x => x.PrincipalId); platformAdministrator.HasOne<PrincipalRow>().WithMany().HasForeignKey(x => x.PrincipalId).OnDelete(DeleteBehavior.Cascade);
        var membership = modelBuilder.Entity<TenantMembershipRow>(); membership.ToTable("TenantMemberships"); membership.HasKey(x => x.Id); membership.Property(x => x.PrincipalId).HasColumnName("UserId"); membership.HasIndex(x => new { x.TenantId, x.PrincipalId }).IsUnique(); membership.HasOne<TenantRow>().WithMany().HasForeignKey(x => x.TenantId).OnDelete(DeleteBehavior.Cascade); membership.HasOne<PrincipalRow>().WithMany().HasForeignKey(x => x.PrincipalId).OnDelete(DeleteBehavior.Cascade);
        var workspaceMembership = modelBuilder.Entity<WorkspaceMembershipRow>(); workspaceMembership.ToTable("WorkspaceMemberships"); workspaceMembership.HasKey(x => x.Id); workspaceMembership.HasIndex(x => new { x.WorkspaceId, x.PrincipalId }).IsUnique(); workspaceMembership.HasIndex(x => x.PrincipalId); workspaceMembership.HasOne<WorkspaceRow>().WithMany().HasForeignKey(x => x.WorkspaceId).OnDelete(DeleteBehavior.Cascade); workspaceMembership.HasOne<PrincipalRow>().WithMany().HasForeignKey(x => x.PrincipalId).OnDelete(DeleteBehavior.Cascade);
        var role = modelBuilder.Entity<RoleDefinitionRow>(); role.ToTable("RoleDefinitions"); role.HasKey(x => x.Id); role.HasIndex(x => x.Name).IsUnique();
        var assignment = modelBuilder.Entity<RoleAssignmentRow>(); assignment.ToTable("RoleAssignments"); assignment.HasKey(x => x.Id); assignment.HasIndex(x => new { x.TenantId, x.PrincipalId }); assignment.HasIndex(x => new { x.TenantId, x.Scope }); assignment.HasIndex(x => new { x.TenantId, x.PrincipalId, x.RoleDefinitionId, x.Scope }).IsUnique();
        var audit = modelBuilder.Entity<SecurityAuditRow>(); audit.ToTable("SecurityAuditEvents"); audit.HasKey(x => x.Id); audit.Property(x => x.Action).HasMaxLength(128); audit.Property(x => x.ReasonCode).HasMaxLength(64); audit.Property(x => x.CorrelationId).HasMaxLength(64); audit.HasIndex(x => new { x.OccurredAtUtcTicks, x.Id }); audit.HasIndex(x => x.Action); audit.HasIndex(x => x.ActorPrincipalId); audit.HasIndex(x => x.TargetPrincipalId);
    }
}

internal static class SqliteIdentitySchema
{
    public static async Task EnsureAsync(ControlPlaneDbContext context, CancellationToken cancellationToken)
    {
        var connection = context.Database.GetDbConnection();
        if (connection.State != ConnectionState.Open) await connection.OpenAsync(cancellationToken);
        await AddColumnIfMissingAsync(connection, "ControlPlaneResources", "TenantId", "TEXT NULL", cancellationToken);
        await AddColumnIfMissingAsync(connection, "ControlPlaneResources", "WorkspaceId", "TEXT NULL", cancellationToken);
        await AddColumnIfMissingAsync(connection, "ControlPlaneResources", "Uid", "TEXT NULL", cancellationToken);
        await AddColumnIfMissingAsync(connection, "ControlPlaneResources", "Kind", "TEXT NULL", cancellationToken);
        await AddColumnIfMissingAsync(connection, "ControlPlaneResources", "Name", "TEXT NULL", cancellationToken);
        string[] commands =
        [
            "CREATE TABLE IF NOT EXISTS Tenants (Id TEXT NOT NULL PRIMARY KEY, Name TEXT NOT NULL, DisplayName TEXT NOT NULL, Status INTEGER NOT NULL, CreatedAt TEXT NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS IX_Tenants_Name ON Tenants(Name);",
            "CREATE TABLE IF NOT EXISTS Workspaces (Id TEXT NOT NULL PRIMARY KEY, TenantId TEXT NOT NULL, Name TEXT NOT NULL, DisplayName TEXT NOT NULL, Status INTEGER NOT NULL, CreatedAt TEXT NOT NULL, FOREIGN KEY(TenantId) REFERENCES Tenants(Id) ON DELETE CASCADE); CREATE UNIQUE INDEX IF NOT EXISTS IX_Workspaces_TenantId_Name ON Workspaces(TenantId, Name);",
            "CREATE TABLE IF NOT EXISTS Users (Id TEXT NOT NULL PRIMARY KEY, ExternalSubject TEXT NULL, DisplayName TEXT NOT NULL, Email TEXT NULL, Status INTEGER NOT NULL, CreatedAt TEXT NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS IX_Users_ExternalSubject ON Users(ExternalSubject);",
            "CREATE TABLE IF NOT EXISTS TenantMemberships (Id TEXT NOT NULL PRIMARY KEY, TenantId TEXT NOT NULL, UserId TEXT NOT NULL, Status INTEGER NOT NULL, JoinedAt TEXT NOT NULL, FOREIGN KEY(TenantId) REFERENCES Tenants(Id) ON DELETE CASCADE, FOREIGN KEY(UserId) REFERENCES Users(Id) ON DELETE CASCADE); CREATE UNIQUE INDEX IF NOT EXISTS IX_TenantMemberships_TenantId_UserId ON TenantMemberships(TenantId, UserId);",
            "CREATE TABLE IF NOT EXISTS ExternalIdentities (Id TEXT NOT NULL PRIMARY KEY, Issuer TEXT NOT NULL, Subject TEXT NOT NULL, PrincipalId TEXT NOT NULL, LinkedAt TEXT NOT NULL, FOREIGN KEY(PrincipalId) REFERENCES Users(Id) ON DELETE CASCADE); CREATE UNIQUE INDEX IF NOT EXISTS IX_ExternalIdentities_Issuer_Subject ON ExternalIdentities(Issuer, Subject); CREATE INDEX IF NOT EXISTS IX_ExternalIdentities_PrincipalId ON ExternalIdentities(PrincipalId);",
            "CREATE TABLE IF NOT EXISTS LocalIdentities (AccountId TEXT NOT NULL PRIMARY KEY, PrincipalId TEXT NOT NULL, LinkedAt TEXT NOT NULL, FOREIGN KEY(PrincipalId) REFERENCES Users(Id) ON DELETE CASCADE); CREATE UNIQUE INDEX IF NOT EXISTS IX_LocalIdentities_PrincipalId ON LocalIdentities(PrincipalId);",
            "CREATE TABLE IF NOT EXISTS PlatformAdministrators (PrincipalId TEXT NOT NULL PRIMARY KEY, GrantedAt TEXT NOT NULL, FOREIGN KEY(PrincipalId) REFERENCES Users(Id) ON DELETE CASCADE);",
            "CREATE TABLE IF NOT EXISTS WorkspaceMemberships (Id TEXT NOT NULL PRIMARY KEY, WorkspaceId TEXT NOT NULL, PrincipalId TEXT NOT NULL, Status INTEGER NOT NULL, JoinedAt TEXT NOT NULL, FOREIGN KEY(WorkspaceId) REFERENCES Workspaces(Id) ON DELETE CASCADE, FOREIGN KEY(PrincipalId) REFERENCES Users(Id) ON DELETE CASCADE); CREATE UNIQUE INDEX IF NOT EXISTS IX_WorkspaceMemberships_WorkspaceId_PrincipalId ON WorkspaceMemberships(WorkspaceId, PrincipalId); CREATE INDEX IF NOT EXISTS IX_WorkspaceMemberships_PrincipalId ON WorkspaceMemberships(PrincipalId);",
            "CREATE TABLE IF NOT EXISTS RoleDefinitions (Id TEXT NOT NULL PRIMARY KEY, Name TEXT NOT NULL, DisplayName TEXT NOT NULL, PermissionsJson TEXT NOT NULL, IsBuiltIn INTEGER NOT NULL); CREATE UNIQUE INDEX IF NOT EXISTS IX_RoleDefinitions_Name ON RoleDefinitions(Name);",
            "CREATE TABLE IF NOT EXISTS RoleAssignments (Id TEXT NOT NULL PRIMARY KEY, TenantId TEXT NOT NULL, PrincipalId TEXT NOT NULL, PrincipalType INTEGER NOT NULL, RoleDefinitionId TEXT NOT NULL, Scope TEXT NOT NULL); CREATE INDEX IF NOT EXISTS IX_RoleAssignments_TenantId_PrincipalId ON RoleAssignments(TenantId, PrincipalId); CREATE INDEX IF NOT EXISTS IX_RoleAssignments_TenantId_Scope ON RoleAssignments(TenantId, Scope); CREATE UNIQUE INDEX IF NOT EXISTS IX_RoleAssignments_Unique ON RoleAssignments(TenantId, PrincipalId, RoleDefinitionId, Scope);",
            "CREATE TABLE IF NOT EXISTS SecurityAuditEvents (Id TEXT NOT NULL PRIMARY KEY, Action TEXT NOT NULL, Outcome INTEGER NOT NULL, ActorPrincipalId TEXT NULL, TargetPrincipalId TEXT NULL, TargetAccountId TEXT NULL, TenantId TEXT NULL, WorkspaceId TEXT NULL, ReasonCode TEXT NULL, CorrelationId TEXT NULL, OccurredAtUtcTicks INTEGER NOT NULL); CREATE INDEX IF NOT EXISTS IX_SecurityAuditEvents_OccurredAtUtcTicks_Id ON SecurityAuditEvents(OccurredAtUtcTicks, Id); CREATE INDEX IF NOT EXISTS IX_SecurityAuditEvents_Action ON SecurityAuditEvents(Action); CREATE INDEX IF NOT EXISTS IX_SecurityAuditEvents_ActorPrincipalId ON SecurityAuditEvents(ActorPrincipalId); CREATE INDEX IF NOT EXISTS IX_SecurityAuditEvents_TargetPrincipalId ON SecurityAuditEvents(TargetPrincipalId);",
            "DROP INDEX IF EXISTS IX_ControlPlaneResources_LogicalIdentity; CREATE UNIQUE INDEX IF NOT EXISTS IX_ControlPlaneResources_LogicalIdentity ON ControlPlaneResources(WorkspaceId, Namespace, Kind, Name);"
        ];
        foreach (var sql in commands) await context.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        await AddColumnIfMissingAsync(connection, "Users", "Kind", "INTEGER NOT NULL DEFAULT 0", cancellationToken);
        await context.Database.ExecuteSqlRawAsync(
            "INSERT OR IGNORE INTO ExternalIdentities (Id, Issuer, Subject, PrincipalId, LinkedAt) SELECT lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), 'https://agentstration.local/development', ExternalSubject, Id, CreatedAt FROM Users WHERE ExternalSubject IS NOT NULL",
            cancellationToken);
        await context.Database.ExecuteSqlRawAsync(
            "INSERT OR IGNORE INTO WorkspaceMemberships (Id, WorkspaceId, PrincipalId, Status, JoinedAt) SELECT lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random()) % 4 + 1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6))), Workspaces.Id, TenantMemberships.UserId, TenantMemberships.Status, TenantMemberships.JoinedAt FROM TenantMemberships JOIN Workspaces ON Workspaces.TenantId = TenantMemberships.TenantId",
            cancellationToken);
    }

    private static async Task AddColumnIfMissingAsync(System.Data.Common.DbConnection connection, string table, string column, string definition, CancellationToken cancellationToken)
    {
        await using var check = connection.CreateCommand(); check.CommandText = $"PRAGMA table_info({table})";
        await using var reader = await check.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken)) if (string.Equals(reader.GetString(1), column, StringComparison.OrdinalIgnoreCase)) return;
        await reader.DisposeAsync();
        await using var alter = connection.CreateCommand(); alter.CommandText = $"ALTER TABLE {table} ADD COLUMN {column} {definition}"; await alter.ExecuteNonQueryAsync(cancellationToken);
    }
}

public sealed class SqliteIdentityStore(IDbContextFactory<ControlPlaneDbContext> contextFactory) : IIdentityStore, ISecurityAuditStore
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);
    public async Task<Tenant?> FindTenantByNameAsync(string name, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.Tenants.AsNoTracking().SingleOrDefaultAsync(x => x.Name == name, token)); }
    public async Task<Tenant?> GetTenantAsync(Guid id, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.Tenants.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, token)); }
    public async Task<IReadOnlyList<Tenant>> ListTenantsAsync(CancellationToken token) { await using var db = await CreateAsync(token); return (await db.Tenants.AsNoTracking().OrderBy(x => x.Name).ToArrayAsync(token)).Select(x => Map(x)!).ToArray(); }
    public Task AddTenantAsync(Tenant x, CancellationToken token) => AddAsync(db => db.Tenants.Add(new() { Id = x.Id, Name = x.Name, DisplayName = x.DisplayName, Status = x.Status, CreatedAt = x.CreatedAt }), token);
    public async Task<Workspace?> FindWorkspaceByNameAsync(Guid tenantId, string name, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.Workspaces.AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenantId && x.Name == name, token)); }
    public async Task<Workspace?> GetWorkspaceAsync(Guid id, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.Workspaces.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, token)); }
    public async Task<Workspace?> GetWorkspaceAsync(Guid tenantId, Guid id, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.Workspaces.AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenantId && x.Id == id, token)); }
    public async Task<IReadOnlyList<Workspace>> ListWorkspacesAsync(Guid tenantId, CancellationToken token) { await using var db = await CreateAsync(token); return (await db.Workspaces.AsNoTracking().Where(x => x.TenantId == tenantId).OrderBy(x => x.Name).ToArrayAsync(token)).Select(x => Map(x)!).ToArray(); }
    public Task AddWorkspaceAsync(Workspace x, CancellationToken token) => AddAsync(db => db.Workspaces.Add(new() { Id = x.Id, TenantId = x.TenantId, Name = x.Name, DisplayName = x.DisplayName, Status = x.Status, CreatedAt = x.CreatedAt }), token);
    public async Task<Principal?> GetPrincipalAsync(Guid id, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.Principals.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, token)); }
    public Task AddPrincipalAsync(Principal x, CancellationToken token) => AddAsync(db => db.Principals.Add(new() { Id = x.Id, Kind = x.Kind, DisplayName = x.DisplayName, Email = x.Email, Status = x.Status, CreatedAt = x.CreatedAt }), token);
    public async Task UpdatePrincipalAsync(Principal x, CancellationToken token) { await using var db = await CreateAsync(token); var row = await db.Principals.SingleOrDefaultAsync(value => value.Id == x.Id, token) ?? throw new KeyNotFoundException($"Principal '{x.Id}' was not found."); row.Kind = x.Kind; row.DisplayName = x.DisplayName; row.Email = x.Email; row.Status = x.Status; try { await db.SaveChangesAsync(token); } catch (DbUpdateException ex) { throw new ControlPlaneConcurrencyException(ex.InnerException?.Message ?? ex.Message); } }
    public async Task<ExternalIdentity?> FindExternalIdentityAsync(string issuer, string subject, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.ExternalIdentities.AsNoTracking().SingleOrDefaultAsync(x => x.Issuer == issuer && x.Subject == subject, token)); }
    public async Task<IReadOnlyList<ExternalIdentity>> ListExternalIdentitiesAsync(Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return (await db.ExternalIdentities.AsNoTracking().Where(x => x.PrincipalId == principalId).OrderBy(x => x.Issuer).ThenBy(x => x.Subject).ToArrayAsync(token)).Select(x => Map(x)!).ToArray(); }
    public Task AddExternalIdentityAsync(ExternalIdentity x, CancellationToken token) => AddAsync(db => db.ExternalIdentities.Add(new() { Id = x.Id, Issuer = x.Issuer, Subject = x.Subject, PrincipalId = x.PrincipalId, LinkedAt = x.LinkedAt }), token);
    public async Task RemoveExternalIdentityAsync(Guid principalId, Guid externalIdentityId, CancellationToken token) { await using var db = await CreateAsync(token); var row = await db.ExternalIdentities.SingleOrDefaultAsync(x => x.PrincipalId == principalId && x.Id == externalIdentityId, token); if (row is null) return; db.ExternalIdentities.Remove(row); await db.SaveChangesAsync(token); }
    public async Task<LocalIdentity?> FindLocalIdentityAsync(Guid accountId, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.LocalIdentities.AsNoTracking().SingleOrDefaultAsync(x => x.AccountId == accountId, token)); }
    public async Task<LocalIdentity?> FindLocalIdentityByPrincipalAsync(Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.LocalIdentities.AsNoTracking().SingleOrDefaultAsync(x => x.PrincipalId == principalId, token)); }
    public async Task<IReadOnlyList<LocalIdentity>> ListLocalIdentitiesAsync(CancellationToken token) { await using var db = await CreateAsync(token); return (await db.LocalIdentities.AsNoTracking().OrderBy(x => x.AccountId).ToArrayAsync(token)).Select(x => Map(x)!).ToArray(); }
    public Task AddLocalIdentityAsync(LocalIdentity x, CancellationToken token) => AddAsync(db => db.LocalIdentities.Add(new() { AccountId = x.AccountId, PrincipalId = x.PrincipalId, LinkedAt = x.LinkedAt }), token);
    public async Task<bool> IsPlatformAdministratorAsync(Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return await db.PlatformAdministrators.AsNoTracking().AnyAsync(x => x.PrincipalId == principalId, token); }
    public async Task<PlatformAdministrator?> GetPlatformAdministratorAsync(Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.PlatformAdministrators.AsNoTracking().SingleOrDefaultAsync(x => x.PrincipalId == principalId, token)); }
    public async Task<IReadOnlyList<PlatformAdministrator>> ListPlatformAdministratorsAsync(CancellationToken token) { await using var db = await CreateAsync(token); return (await db.PlatformAdministrators.AsNoTracking().ToArrayAsync(token)).OrderBy(x => x.GrantedAt).Select(x => Map(x)!).ToArray(); }
    public Task AddPlatformAdministratorAsync(PlatformAdministrator x, CancellationToken token) => AddAsync(db => db.PlatformAdministrators.Add(new() { PrincipalId = x.PrincipalId, GrantedAt = x.GrantedAt }), token);
    public async Task RemovePlatformAdministratorAsync(Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); var row = await db.PlatformAdministrators.SingleOrDefaultAsync(x => x.PrincipalId == principalId, token); if (row is null) return; db.PlatformAdministrators.Remove(row); await db.SaveChangesAsync(token); }
    public async Task<TenantMembership?> FindMembershipAsync(Guid tenantId, Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.TenantMemberships.AsNoTracking().SingleOrDefaultAsync(x => x.TenantId == tenantId && x.PrincipalId == principalId, token)); }
    public async Task<IReadOnlyList<TenantMembership>> ListMembershipsAsync(Guid tenantId, CancellationToken token) { await using var db = await CreateAsync(token); return (await db.TenantMemberships.AsNoTracking().Where(x => x.TenantId == tenantId).ToArrayAsync(token)).Select(x => Map(x)!).ToArray(); }
    public Task AddMembershipAsync(TenantMembership x, CancellationToken token) => AddAsync(db => db.TenantMemberships.Add(new() { Id = x.Id, TenantId = x.TenantId, PrincipalId = x.PrincipalId, Status = x.Status, JoinedAt = x.JoinedAt }), token);
    public async Task<WorkspaceMembership?> FindWorkspaceMembershipAsync(Guid workspaceId, Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.WorkspaceMemberships.AsNoTracking().SingleOrDefaultAsync(x => x.WorkspaceId == workspaceId && x.PrincipalId == principalId, token)); }
    public async Task<IReadOnlyList<WorkspaceMembership>> ListWorkspaceMembershipsAsync(Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return (await db.WorkspaceMemberships.AsNoTracking().Where(x => x.PrincipalId == principalId).ToArrayAsync(token)).Select(x => Map(x)!).ToArray(); }
    public async Task<IReadOnlyList<WorkspaceMembership>> ListWorkspaceMembersAsync(Guid workspaceId, CancellationToken token) { await using var db = await CreateAsync(token); return (await db.WorkspaceMemberships.AsNoTracking().Where(x => x.WorkspaceId == workspaceId).ToArrayAsync(token)).OrderBy(x => x.JoinedAt).Select(x => Map(x)!).ToArray(); }
    public Task AddWorkspaceMembershipAsync(WorkspaceMembership x, CancellationToken token) => AddAsync(db => db.WorkspaceMemberships.Add(new() { Id = x.Id, WorkspaceId = x.WorkspaceId, PrincipalId = x.PrincipalId, Status = x.Status, JoinedAt = x.JoinedAt }), token);
    public async Task UpdateWorkspaceMembershipAsync(WorkspaceMembership x, CancellationToken token) { await using var db = await CreateAsync(token); var row = await db.WorkspaceMemberships.SingleAsync(value => value.Id == x.Id, token); row.Status = x.Status; await db.SaveChangesAsync(token); }
    public async Task RemoveWorkspaceMembershipAsync(Guid id, CancellationToken token) { await using var db = await CreateAsync(token); var row = await db.WorkspaceMemberships.SingleOrDefaultAsync(value => value.Id == id, token); if (row is null) return; db.WorkspaceMemberships.Remove(row); await db.SaveChangesAsync(token); }
    public async Task<RoleDefinition?> FindRoleDefinitionByNameAsync(string name, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.RoleDefinitions.AsNoTracking().SingleOrDefaultAsync(x => x.Name == name, token)); }
    public async Task<RoleDefinition?> GetRoleDefinitionAsync(Guid id, CancellationToken token) { await using var db = await CreateAsync(token); return Map(await db.RoleDefinitions.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, token)); }
    public Task AddRoleDefinitionAsync(RoleDefinition x, CancellationToken token) => AddAsync(db => db.RoleDefinitions.Add(new() { Id = x.Id, Name = x.Name, DisplayName = x.DisplayName, PermissionsJson = JsonSerializer.Serialize(x.Permissions, JsonOptions), IsBuiltIn = x.IsBuiltIn }), token);
    public async Task<IReadOnlyList<RoleAssignment>> ListRoleAssignmentsAsync(Guid tenantId, Guid principalId, CancellationToken token) { await using var db = await CreateAsync(token); return (await db.RoleAssignments.AsNoTracking().Where(x => x.TenantId == tenantId && x.PrincipalId == principalId).ToArrayAsync(token)).Select(x => Map(x)!).ToArray(); }
    public Task AddRoleAssignmentAsync(RoleAssignment x, CancellationToken token) => AddAsync(db => db.RoleAssignments.Add(new() { Id = x.Id, TenantId = x.TenantId, PrincipalId = x.PrincipalId, PrincipalType = x.PrincipalType, RoleDefinitionId = x.RoleDefinitionId, Scope = x.Scope }), token);
    public async Task RemoveRoleAssignmentAsync(Guid id, CancellationToken token) { await using var db = await CreateAsync(token); var row = await db.RoleAssignments.SingleOrDefaultAsync(value => value.Id == id, token); if (row is null) return; db.RoleAssignments.Remove(row); await db.SaveChangesAsync(token); }
    public Task AppendAsync(SecurityAuditEvent x, CancellationToken token) => AddAsync(db => db.SecurityAuditEvents.Add(new() { Id = x.Id, Action = x.Action, Outcome = x.Outcome, ActorPrincipalId = x.ActorPrincipalId, TargetPrincipalId = x.TargetPrincipalId, TargetAccountId = x.TargetAccountId, TenantId = x.TenantId, WorkspaceId = x.WorkspaceId, ReasonCode = x.ReasonCode, CorrelationId = x.CorrelationId, OccurredAtUtcTicks = x.OccurredAt.UtcTicks }), token);
    public async Task<IReadOnlyList<SecurityAuditEvent>> ListLatestAsync(int limit, CancellationToken token) { await using var db = await CreateAsync(token); return (await db.SecurityAuditEvents.AsNoTracking().OrderByDescending(x => x.OccurredAtUtcTicks).ThenByDescending(x => x.Id).Take(Math.Clamp(limit, 1, 200)).ToArrayAsync(token)).Select(Map).ToArray(); }
    private async Task<ControlPlaneDbContext> CreateAsync(CancellationToken token) => await contextFactory.CreateDbContextAsync(token);
    private async Task AddAsync(Action<ControlPlaneDbContext> add, CancellationToken token) { await using var db = await CreateAsync(token); add(db); try { await db.SaveChangesAsync(token); } catch (DbUpdateException ex) { throw new ControlPlaneConcurrencyException(ex.InnerException?.Message ?? ex.Message); } }
    private static Tenant? Map(TenantRow? x) => x is null ? null : new(x.Id, x.Name, x.DisplayName, x.Status, x.CreatedAt);
    private static Workspace? Map(WorkspaceRow? x) => x is null ? null : new(x.Id, x.TenantId, x.Name, x.DisplayName, x.Status, x.CreatedAt);
    private static Principal? Map(PrincipalRow? x) => x is null ? null : new(x.Id, x.Kind, x.DisplayName, x.Email, x.Status, x.CreatedAt);
    private static ExternalIdentity? Map(ExternalIdentityRow? x) => x is null ? null : new(x.Id, x.Issuer, x.Subject, x.PrincipalId, x.LinkedAt);
    private static LocalIdentity? Map(LocalIdentityRow? x) => x is null ? null : new(x.AccountId, x.PrincipalId, x.LinkedAt);
    private static PlatformAdministrator? Map(PlatformAdministratorRow? x) => x is null ? null : new(x.PrincipalId, x.GrantedAt);
    private static TenantMembership? Map(TenantMembershipRow? x) => x is null ? null : new(x.Id, x.TenantId, x.PrincipalId, x.Status, x.JoinedAt);
    private static WorkspaceMembership? Map(WorkspaceMembershipRow? x) => x is null ? null : new(x.Id, x.WorkspaceId, x.PrincipalId, x.Status, x.JoinedAt);
    private static RoleDefinition? Map(RoleDefinitionRow? x) => x is null ? null : new(x.Id, x.Name, x.DisplayName, JsonSerializer.Deserialize<string[]>(x.PermissionsJson, JsonOptions) ?? [], x.IsBuiltIn);
    private static RoleAssignment? Map(RoleAssignmentRow? x) => x is null ? null : new(x.Id, x.TenantId, x.PrincipalId, x.PrincipalType, x.RoleDefinitionId, x.Scope);
    private static SecurityAuditEvent Map(SecurityAuditRow x) => new(x.Id, x.Action, x.Outcome, x.ActorPrincipalId, x.TargetPrincipalId, x.TargetAccountId, x.TenantId, x.WorkspaceId, x.ReasonCode, x.CorrelationId, new DateTimeOffset(x.OccurredAtUtcTicks, TimeSpan.Zero));
}
