// <auto-generated />
using System;
using Agentstration.Flow.Storage.PostgreSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Agentstration.Flow.Storage.PostgreSql.Migrations
{
    [DbContext(typeof(FlowDbContext))]
    [Migration("20260903061012_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flow")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Agentstration.Flow.Storage.PostgreSql.FlowDocument", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ETag")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FlowId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Version")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("WorkspaceId", "Namespace", "Kind", "FlowId", "Version");

                    b.HasIndex("WorkspaceId", "Kind", "TenantId", "PrincipalId", "UpdatedAt", "Key");

                    b.HasIndex("WorkspaceId", "Kind", "TenantId", "PrincipalId", "Status", "UpdatedAt", "Key");

                    b.HasIndex("WorkspaceId", "Kind", "TenantId", "PrincipalId", "Namespace", "FlowId", "UpdatedAt", "Key");

                    b.HasIndex("WorkspaceId", "Kind", "TenantId", "PrincipalId", "Namespace", "FlowId", "Status", "UpdatedAt", "Key")
                        .HasDatabaseName("IX_FlowResources_WorkspaceId_Kind_TenantId_PrincipalId_Namesp~1");

                    b.ToTable("FlowResources", "flow");
                });
#pragma warning restore 612, 618
        }
    }
}
