<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="../ApiModuleGlobalUsings.cs" Link="GlobalUsings.cs" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../Agentstration.Api.Contracts/Agentstration.Api.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.ResourceManagement/Agentstration.ResourceManagement.csproj" />
    <ProjectReference Include="../Agentstration.Resources/Agentstration.Resources.csproj" />
    <ProjectReference Include="../Agentstration.Secrets/Agentstration.Secrets.csproj" />
    <ProjectReference Include="../Agentstration.Secrets.Contracts/Agentstration.Secrets.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.Sources.Contracts/Agentstration.Sources.Contracts.csproj" />
  </ItemGroup>
</Project>
