<Project Sdk="MSTest.Sdk/4.3.3">
  <ItemGroup>
    <ProjectReference Include="../../src/Agentstration.ModelProviders/Agentstration.ModelProviders.csproj" />
    <ProjectReference Include="../../src/Agentstration.Aep.Abstractions/Agentstration.Aep.Abstractions.csproj" />
    <ProjectReference Include="../../src/Agentstration.Aep.AspNetCore/Agentstration.Aep.AspNetCore.csproj" />
    <ProjectReference Include="../../src/Agentstration.Aep.Client/Agentstration.Aep.Client.csproj" />
    <ProjectReference Include="../../src/Agentstration.Aep.MicrosoftExtensionsAI/Agentstration.Aep.MicrosoftExtensionsAI.csproj" />
    <ProjectReference Include="../../src/Agentstration.Extensions.Ollama/Agentstration.Extensions.Ollama.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
</Project>
