<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="../ApiModuleGlobalUsings.cs" Link="GlobalUsings.cs" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../aep/src/Agentstration.Aep.Abstractions/Agentstration.Aep.Abstractions.csproj" />
    <ProjectReference Include="../Agentstration.Api.Contracts/Agentstration.Api.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.Extensions/Agentstration.Extensions.csproj" />
    <ProjectReference Include="../Agentstration.Extensions.Contracts/Agentstration.Extensions.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.Extensions.Aep/Agentstration.Extensions.Aep.csproj" />
    <ProjectReference Include="../Agentstration.Identity.Contracts/Agentstration.Identity.Contracts.csproj" />
    <ProjectReference Include="../Agentstration.ResourceManagement/Agentstration.ResourceManagement.csproj" />
    <ProjectReference Include="../Agentstration.Resources/Agentstration.Resources.csproj" />
  </ItemGroup>
</Project>
